import { JobSource } from './types.js';

export const INITIAL_JOB_SOURCES: JobSource[] = [
  {
    id: 'src-tpsc-01',
    name: 'Tripura Public Service Commission (TPSC)',
    organization: 'Tripura Public Service Commission',
    url: 'https://tpsc.tripura.gov.in',
    source_type: 'STATE_COMMISSION',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-trbt-02',
    name: "Teachers' Recruitment Board, Tripura (TRBT)",
    organization: 'TRBT - Education (School) Dept',
    url: 'https://trb.tripura.gov.in',
    source_type: 'BOARD',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-jrbt-03',
    name: 'Joint Recruitment Board, Tripura (JRBT)',
    organization: 'Directorate of Employment Services & Manpower Planning',
    url: 'https://employment.tripura.gov.in',
    source_type: 'BOARD',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-police-04',
    name: 'Tripura Police Recruitment Board',
    organization: 'Tripura Police, Home Department',
    url: 'https://tripurapolice.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-thc-05',
    name: 'High Court of Tripura Recruitment Cell',
    organization: 'High Court of Tripura, Agartala',
    url: 'https://thc.nic.in',
    source_type: 'JUDICIARY',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-health-06',
    name: 'Directorate of Health Services & NHM Tripura',
    organization: 'Health & Family Welfare Dept, Govt of Tripura',
    url: 'https://health.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 7).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 7).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-nita-07',
    name: 'National Institute of Technology Agartala (NIT)',
    organization: 'NIT Agartala (Institute of National Importance)',
    url: 'https://www.nita.ac.in',
    source_type: 'UNIVERSITY',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-tripurauniv-08',
    name: 'Tripura University (Central University)',
    organization: 'Tripura University, Suryamaninagar',
    url: 'https://www.tripurauniv.ac.in',
    source_type: 'UNIVERSITY',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 9).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 9).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-mbb-09',
    name: 'Maharaja Bir Bikram (MBB) University',
    organization: 'MBB University, Agartala',
    url: 'https://mbbuniversity.ac.in',
    source_type: 'UNIVERSITY',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 10).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 10).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-stateportal-10',
    name: 'Official Tripura State Portal Circulars',
    organization: 'Government of Tripura General Administration',
    url: 'https://tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-sscer-11',
    name: 'Staff Selection Commission - Eastern Region (Tripura)',
    organization: 'Staff Selection Commission (Govt of India)',
    url: 'https://sscer.org',
    source_type: 'CENTRAL_GOVT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-forest-12',
    name: 'Tripura Forest Department',
    organization: 'Forest Department, Govt of Tripura',
    url: 'https://forest.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    last_success_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'src-rd-13',
    name: 'Rural Development Department (RD) Tripura',
    organization: 'Rural Development Department, Govt of Tripura',
    url: 'https://rural.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'src-dit-14',
    name: 'Directorate of Information Technology (DIT) Tripura',
    organization: 'Information Technology Department, Govt of Tripura',
    url: 'https://it.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'src-tsecl-15',
    name: 'Tripura State Electricity Corporation Ltd (TSECL)',
    organization: 'Power Department / TSECL, Govt of Tripura',
    url: 'https://www.tsecl.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'src-trlm-16',
    name: 'Tripura Rural Livelihood Mission (TRLM)',
    organization: 'Rural Development / TRLM, Govt of Tripura',
    url: 'https://trlm.tripura.gov.in',
    source_type: 'BOARD',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'src-swse-17',
    name: 'Social Welfare & Social Education (SWSE) Tripura',
    organization: 'Social Welfare Department, Govt of Tripura',
    url: 'https://socialwelfare.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'src-krishi-18',
    name: 'Agriculture & Farmers Welfare Department (Krishi)',
    organization: 'Agriculture Department, Govt of Tripura',
    url: 'https://krishi.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'src-panchayat-19',
    name: 'Panchayat Department Tripura',
    organization: 'Panchayat Department, Govt of Tripura',
    url: 'https://panchayat.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'src-udd-20',
    name: 'Urban Development Department (UDD) Tripura',
    organization: 'Urban Development Department, Govt of Tripura',
    url: 'https://urbandevelopment.tripura.gov.in',
    source_type: 'STATE_DEPT',
    active: true,
    scan_frequency: 'DAILY',
    last_scanned_at: new Date().toISOString(),
    last_success_at: new Date().toISOString(),
    last_error: null,
    http_status: 200,
    created_at: new Date().toISOString(),
  }
];
